---
title: Dream Diary 1
tags: dream_diary
author: natto
enabletoc: true
---

*WARNING: Highly chuunibyou content*

* What
** Why
So I, more often than not, have really fun dreams (sometimes even lucid). I shall be writing them down now as records for the public but only those ones that really, really do affect me.

** What dreams
I usually have dreams in a two phase system where I see two dreams in one night because one of them gets disrupted when I wake up in between. So when I have these two phase dreams, I'll be writing only the one that I remember i.e, the second one. Also these will be *short* since I do not remember most of the dream in detail.

#+begin_export html
<!--more-->
#+end_export

** What will be omitted
Anything that I do not remember and everything that I deem insignificant. The backgrounds and the noises, like most other dreams, do not make sense and make you feel like you are on drugs, so I might omit those as well since they will be a recurring thing.

* Format
The text in [[dream][Dream]] follows the following syntax
- =verbatim= :: Post wakeup thoughts or analysis.
- /italic/ :: Real life connections in the dream.
- +strike+ :: Improbable things.

* <<dream>> Dream
I find myself in a local Delhi street, trying to buy Kulfi-Falooda off a street vendor, who runs out of it just then. He asks me to wait until he restocks it. So I wait and wait and he goes "Sorry, we do not serve Kulfi-Falooda anymore since it is not profitable for us now." This leaves me completely devastated and I start screaming really loud.

The ground below me starts to disappear as I fall into an endless pit of void. Suddenly, the environment changed, this time, a greenhouse. I turn around and find severely-out-of-place chemistry lab equipment on the shelf. Walking out of there, I find out that this was in fact, a school. There was an absurd amount pretty girls and handsome boys walking all around. I feel a little overwhelmed and suddenly notice the backpack on me. I reach in and find a card that says

#+begin_src
a.
#+end_src

Then immediately I rush back into the greenhouse to find two people in lab coats /similar to what I had to wear in my school labs/. They were doing something with the lab equipment, then it dawned upon me that they were synthesising methamphetamine. They noticed me and immediately rushed and started choking me. I die.

I wake up in a classroom this time. I find myself around a group of people who are apparently my friends. I suddenly realise that I switch timelines everytime on random triggers. Weirdly enough, I kept talking with them as if I knew them for a long time. Suddenly, black clouds start covering up the outside sky. Five beautiful humanoid girls spawn in as if this was a game of Apex Legends. =I remember none of the names in the dream except one of these girls, which I will talk about later. For now, let's name these girls W, V, X, Y and Z=. They come forward claiming that they have been sent by the +lower gods+ and they must marry me. Surprisingly enough, I was not elated or amused, instead I was frustrated, =frustrated similar to how I have been for the past few months over some trivial things that no one will probably understand=.

The girls do not particularly seem very interested in me and the feeling goes both ways. The teacher comes in and announces a surprise unofficial chemistry class test. Instructions were to attempt any three of the four questions in the paper and I knew answers to all four of them. I start writing and the time speeds up in a very comical fashion. I get super confused, I see a girl sitting next to me, it was one of those five humanoid creatures, =I do not remember her name, but she is the only character I remember the face of=, let's call her W. The teacher announces that there are only 5 minutes left until the bell rings. This completely baffles me, since it has only been 5 minutes since this 90 minute test started. W explains to me, how time sped up only for me and how I must hurry. I can no longer see of feel the presence of V, X, Y and Z by this point. The only things I feel are me, W and the test paper in front of me. I barely finish solving one question and submit the test.

I am unusually shook and W looks at me without saying anything, her eyes trying to console the pitiful me. Then we talk about things =that I do not remember= and she asks me, "Why do you not look into the eyes of people when talking?". =This is a real life trait of mine, I tend to not look into the eyes of the person I am talking to for more than 25% of the conversation=. Then I stare into her eyes and she stares into mine. Although we were not talking, we were still staring into each other's eyes and we continued to do so for a long, really long time. It felt so peaceful, a feeling of transquility entirely engulfed me. Although I am an atheist, it felt like I was talking to some kind of greater power. =I would do anything to feel this kind of calm outside my dreams=. Her calm and composed self broke out of the trance and so did mine. X, Y and Z went back to the sky saying that they do not want to marry me after all. I bid W farewell, she was a bit hesitant to leave me alone but disappeared suddenly in the end anyway. V stayed behind, but with some intention different than the one she came with.

As soon as they go back to where they came from, I faint. I wake up this time at my home except I have an older brother now and V is still there. My brother, G, begins to tell me how there is some kind of cyborg like man living in the street next to ours who has been trying to kill him. We decide to go and kill him together, but first, we decide to grab some lunch at "Vaishnav Bhojanalay", where he decides to smoke a fuckton of cigarettes after eating. After a long delay, we finally reach at our destination. We knock at his door, but the man does not come to the door to greet us. We +break in+ to find that the guy who was running weird experiments and plotting to kill G was Senator Armstrong from Metal Gear Rising. A blade appears in my hand and G starts screaming "RULES OF NATURE". I somehow manage to kill him with no wounds but G steals all the glory. V apparently wanted to marry G, so she hopped in with me to this timeline. =Also, V is the only character, I remember the name of, but I shall not disclose it.= Unable to go back to my timeline, I just start driving my car for no reason with V and G making out in the back for some reason.

And then, I wake up.

* Thoughts
The dream was much weirder than how I described it, as I left out the LSD-like backgrounds and noises. The highlight for me was the second part of the dream. Although in a dream, such peace and tranquility was much needed for me. There were a few more timelines I very vaguely remember, but I cannot write them down since I do not remember enough details. W was just magical, I can still vividly recall her face. I will probably start looking at people more when talking now. I like how I kept reminiscing about the part with W for like fifteen or so minutes after waking up.
