---
title: Feign Chapter 1 - Shadripu
tags: creative_writing, feign
author: AlpaViraam
---
"Ha". Thinking is an arduous task; however, not so much when you have nothing else to do. There he was, staring holes into the supposedly hostile air on this mundane summer day, as if anticipating the end of a decisive battle. /The hellish hours are over now./ He rose with the sluggishness of a dead sloth. His rough, yet feeble arms swept across the table as he tried to wrap things up, stopping briefly as he stared down the silver hourglass on the side for no more than three menacing seconds. The unpolished window doors were slammed shut, as he put his seemingly empty bag over his shoulders. After wiping his already clean hands against his worn-out clothes and checking the door lock for the third time, he finally left his shed of a shop; albeit wearing a poker face.

#+begin_export html
<!--more-->
#+end_export
/Tomorrow is the first day of the festival, a grand opportunity. Something so tedious does not interest me, but it wouldn't hurt if my pocket silver was to clink a little louder./ He walked briskly, lost in his thoughts about the near future concerning him.

"Wrick!", yelled an auburn man of tall stature. The man hurried over in what seemed like an instant. With an unpleasant frown on his glamorous face, the two were now blocking each others' line of sight.

The man looked up with a pained expression that said /I already know why he is here/.

"I will return it as soon as possible", said the man with discomfort written all over his face.

"Oh, you will? It has been six long weeks since then. I hope you do realise that although I am not charging any interest, I am not your friend; nor am I a rich man who can afford to lend so much without any care. Had I known about your lethargic self not being true to your words, I would have not lent you a single dime."

"I am sure you are not pleased with my recent behaviour, allow me to apologise. I'd positively return your money by the upcoming week. I want you to know that I appreciate you doing me this favour given our history, Joun."

"I do not require your appreciation, Doughlebagg! I require my hard-earned money back. The only reason I lent it to you was that we were in the same graduating class."

"I am sorry, but I don't have that much money on me at the moment."

"And how exactly do you plan on securing that money by the next week?"

"There is the upcoming festival; and if I have to, I will mortgage my shop."

"You've got a sense of humour. You will mortgage your entire shop for a mere debt?"

"Please, Joun, my feelings are sincere."

"Fine, next week, but with fifteen percent additional interest."

"You can't be this cruel!"

"Why yes, I can be as cruel as I want. You have always been this way, believing that the things will go the way you want them to go, but not this time."

"Alright, I do not want to see you before seven days have passed then."

The auburn man, Joun Cartingus, took off expressing his disinterest in him. The latter also advanced with quick steps, even quicker than before, betraying his languid demeanour from before. However, it was not long before he had to slow down his steps. He had reached his place of residence, which was just a dingy couple of rooms.

#+begin_center
WRICK HART DOUGHLEBAGG
#+end_center

That is what the nameplate read. The name of this shabby, middle-aged man was Wrick. He went straight to his bed without even changing his clothes. Shabby as they were, he did not have an awful lot of them. There he laid, with his face exhibiting a mix of emotions, primarily disappointment and frustration. It was not soon after that there was a knock on his creaky door. He laid there for a handful of minutes before getting up steadily. This languor was not due to his physical fragility, just an overtaking maneuver by the sin of the sloth kind. It took him a little shy of five whole minutes to open the door.

"Hello, sorry for the delay, how may I help you?"

Only silence prevailed, there was no reply, there was no one at the door, just a piece of paper on the hard stone threshold.

#+begin_src
Do not show your face at the festival.
- Karr
#+end_src

Karr Hart Doughlebagg, Wrick's son, his only child. Wrick closed the door leaving the paper right where he picked it up and went back to his bed.

/So he is back from his expedition to Gordge already, as expected of a prodigy like Karr. I don't want to disrupt his work but the debt is huge, the entirety of three hundred blits, no, three hundred and sixty eight blits must be repaid to Joun, not going to the festival is not an option. It is not like people don't already know that we are related. Dropping his last name didn't help in the slightest; can't blame him for hating me though./

He went back to his room, worrying about his future and ruminating about his past simultaneously. He laid there again, this time, with the daily gazette in his hands. The rest of the evening was spent reading it with a monotonous expression, ending with him going to sleep without any supper; this was not his first time, however. He was in debt but not so poor as to not be able to afford a plain meal.

Again betraying his lazy self, he was up before the sun was. The motivation behind this was simple; today was the day, the first day of the Supra festival. He could pay most, if not all of his debt if he played his cards right today. Mistakes were prohibited today. Nothing is certain except what a man plans in his head, and Wrick was certain about his plans for today. He was trying hard to not be his usual self, would be an understatement. He was dressed in his best clothes, a simple yet elegant attire that outshone the wearer itself, and was probably worn once or twice at most. Mimicking the common populace was not a problem for him, since he was a merchant. Unlike yesterday, he even ate a proper meal for breakfast; a bowl of grainy porridge and some light bread. The unamused old-timer expression was still there but his eyes were determined. Flashy as they were, his looks were not in the slightest, extravagant for a merchant. The door was locked and he was off to a place different from his usual place of work, which was a shabby-looking shop no further than a few hundred meters away from his place of residence.

This time he would be playing merchant at the Pludgin, the cultural centre where all merchant guild members were provided with a fairly small merchant stall. The guild was also responsible for transporting every merchant's goods, which in Wrick's case, unlike other members of the guild, were unsurprisingly not yet transported. However, it was only five in the morning, and the transportation distance was only about ten kilometers since he carefully chose his place near the heart of the eastern city of Bablos, perfectly close to the city's guild office and the Pludgin. By the virtue of his careful planning and the excellent guild services, he never had to buy a horse or a cart. He spared no time getting to the office and issuing the transportation request. The receptionist gave him a mild but mean glare causing him to shift his eyes to the cold, wooden ground. He spent no more time than required at the guild and headed straight to his little old shop with the assigned carriage and its supposed driver.

The carriage was loaded with the selected "goods" which in Wrick's case were an extensive collection of things ranging from delicate glassware and premium quality silk to some silverware and luxury books, written by only the best clerics and writers. His recent purchases of these high-quality expensive goods were the reason he did not make enough money, common people simply could not afford the luxuries he offered while sitting in his small shop like a troll in his cave. But the festival was an excellent opportunity to get rid of these expensive items for good. He was extremely anxious and could not stop thinking about the possible futures awaiting him, but he was not clumsy in the slightest; after all, he was not a mere commoner but a merchant, a member of the guild and had an image to uphold. It was not even an hour and they were already at their destination. He got off and started stacking all his goods under his stall with his sweaty hands, occasionally looking up at the driver for help, only to see his nape and his upright back. Being a single man with no helpers cost him a substantial amount of time but he was done with two hours to spare until noon, the opening time for the public.

With everything set up and some time to kill, he started scouting out potential rivals for the next couple of days. There were familiar faces and some not even native to the city, but none friendly. There was a particularly peculiar stall opposite to his, which had no goods but decks of cards and dice; its cross-eyed owner appeared to be a city local but not one of the people Wrick recognised, which was rare. /A stall for gambling, perhaps?/ The fact that the place was meant to be a public marketplace and not a gambling den earned the stall owner frowns and an unrespectable status among the other stall owners prior to the opening.

As the clock struck twelve, the crowd came rushing in and everyone including Wrick got busy. He expected nothing much, a decent amount of sales would be more than enough to repay his debts, he definitely wanted extra income earlier but now he was satisfied with just being able to repay his debt with as little effort as possible. The busy day was not enough to knock a veteran small-time merchant like Wrick off his feet despite him being used to sitting idle for weeks now. Surprisingly, the gambling stall was full of customers as well, even during the peak afternoon hours, but nobody had time to worry about it.

The crowd thinned as dusk fell rapidly and the only stall with a decent amount of customers was the gambling stall. This did not mean that it was a bad day for others, everyone made fairly large amounts of profit. Wrick was done counting the money and the profits exceeded his debt, he was satisfied with his hard-earned income of seven hundred twenty blits. He was however still wearing the unamused expression that he always wore. Now that his mind was free from worries, at least for today, he could afford to divert his attention to the gambling stall and its owner. He did not particularly have any harsh feelings towards him but was certainly jealous that a merchant like him was falling behind such a man. Now exhausted, his pride took over his emotions out of nowhere. Jealous and curious, with some money to burn, he started moving towards the stall in question with a sharp gold coin worth a hundred blits resting within his tight fist. As he approached the stall, the busy owner turned his head towards this new potential customer, wearing a slight childish grin as he has been since morning. 
