---
title: I am done with ConcourseCI
author: natto
tags: ci, devops, concourse
published: October 20, 2022
modified: October 29, 2022
enabletoc: true
---

* Background
I spent a lot of time (almost entire February/March and random days here and there) on learning concourse, setting it up (under Nomad with Vault on an aarch64 NixOS machine with limited resources, you know which one) and working on resources for it to work with Gitea earlier this year. I spent so much time on something that I am probably never going to use again and I hate myself for it.

#+begin_export html
<!--more-->
#+end_export html

* KIA
What was lost? A lot of time and more time dwelling upon the formerly wasted time. I could have used that time for my many other hobbies or I could have spent more time on other stuff, like programming, that I actually enjoy but lack experience in.

* Why even
I used concourse because of the shills that like to shill every relatively obscure thing out there. Just because it is hard to understand and has sophisticated (arguable) internals does not mean it is practical and fun. I do not hate concourse all that much but it fails to complete my needs and I refuse to work on resources for every little thing, maybe will work on improving the support some time later in the distant future, but not now. It might be good for complicated pipelines but mine are relatively simple.

* Starting over is hard
Starting over again is seriously hard, how will I ever be able to justify the lost time? But ideally, I should not feel the need to justify it.

* What now
I will use DroneCI as soon as I am done with rewiring this stupid pile of messs at my home. It is not much better than concourse but it fits my needs. I am afraid that it might just be another concourse and if that happens, I will give up on self hosting and move completely to GitHub+Actions or GitLab but let's try to avoid that since that is no +pain+ fun. Goodbye concourse, I do not hate you but we cannot be together.

-----

* UPDATE 1
I might just use WoodpeckerCI but it lacks support for Vault. I shall try it regardless since [[https://github.com/woodpecker-ci/woodpecker/pull/915][this PR]] exists.

* UPDATE 2
Okay so I spent an entire day experimenting; and while Woodpecker is very promising, it is stupid simple and thus, lacks what it takes to be a CI for more complex projects. Luckily, I do not have any complex projects, at least not right now. When I do, I shall move back to concourse perhaps and I hope that by that time, there will be multi arch support.

* UPDATE 3
What timing! It is here, they added architecture specification for the registry image resource [[https://github.com/concourse/registry-image-resource/pull/36][here]]. I might go back to concourse in a few days and make a Gitea status resource.

* UPDATE 4
I am dropping the idea of self hosting CI/CD for now because come on, who am I fooling here? I have never written a single code that requires CI/CD and when I do write such a thing, I might as well just use GitHub Actions.
