---
title: Fear
tags: random
author: AlpaViraam
published: September 30, 2023
---

One often wonders if it is possible to attain a better tomorrow - a better future; and if it is, then how? A common question with an obvious answer that it is all rooted in the fear of a worse tomorrow or of a “worse you”. This much is obvious, however, not many attempt to eliminate this fear and instead focus on getting over it by overcoming the trials it sets. Is there something more to it than fear? Is the desire, greed or want driven by this fear? Or is the fear driven by them? Does eliminating the fear eliminate the associated desires, and vice versa? What is the primal nature of this fear and what does it mean to be the “worse you”, when the only “you” is the “you” of the “now”? Many more questions may arise from this very obvious inference. However, do these questions even hold any value over determining whether fear is something to be taken hold of? Or is it some part of you that makes you the person you are? Perhaps it is both, or perhaps it is something that we can completely get rid of and get closer to understanding what it means to realise oneself, that is, the “you”. This text tries a little to explore these questions and possibly get closer to the answer.

* Ideology
Fear is associated with, as petty as they may be, an individual’s ideologies, ambitions, feelings, etc. But the primary and the most important factor is the ideology. Ideologies have surrounded mankind since the dawn of it, it is not something new and nor is it much more advanced than it was in the older times; at least, when it comes to the core values. One may see oneself as an individual with a unique ideology, however, it is a fact that parts of this ideology are shared by many; making it less of an individual thing and more of what would be called a “product” - a product of things greater than the individual. To understand this, we must understand that this product may be a result of influences, feelings, senses, environment and of course, society. Even if a person is to seclude themselves, they are still living on the same planet, experiencing the same emotions and same senses, making them less of an individual but more of a collective idea. This is the part where fear comes in - the ideology or what can also be sometimes called the philosophy is many time so rigid that one would get so attached to it, very much like other material things, like money and family; that it can be a cause of fear for him to instantly get rid of it. Imagine building something up for a long time, perhaps even your entire life and then instantly giving it up when you find something more suited to the truth or subjectively “correct” or “better”. This is no easy feat to do - perhaps even harder than giving up on one’s most treasured belongings like their own children or spouse. Now what does this fear “actually” stem from? Why is it hard to give up on something you worked so hard on? One possible answer might be the individual himself. Encouraging deletion of the already present beliefs might lead one to question the credibility of his own existence or the individualism itself. This might just be the fear of not being “one” as in a separate “one”. As soon as the idea of “one” (or “you”) begins to dissolve, the fear takes hold. What can be inferred from this is that there is no such thing as a “you” - neither of the past, nor of the present and neither worse or better. The entity that is often associated with these idologies is not “you” but “you” is the ideologies themselves; and if we remember from earlier, ideologies are not something alien for every being, it is a shared belief, no matter how much the overlap is. Then why does the “you” and “me” exist? What is the “me” and “you”, and why fear losing it? This all sounds so childish but that is only because it is so. Rigid ideologies, for a lack of a better term, whether religious, political or philosophical, are pretty much the very definition of childish. This is because a “child” lacks, not the understanding of what is and what is not, but the understanding of what may be.

* Ego
Why would one get troubled over abandoning their entire life’s meaning despite knowing very well that their life has no inherent impact? That is due to one’s idea about themselves. We earlier inferred that a person is nothing but his own idea, but it is now time to understand that the idea also includes something along the lines of what is one’s perception of self. Contrary to the popular belief I do not think life is something as romantic as what can be called “absurd”. Abandoning self and attributing happens to this absurdity does hold some truth in it but it comes off as plain lazy. What should be analyzed here is that living is fear; even if you “embrace this absurdity”, you are still living in the constant fear of tomorrow and have your own little ambitions for it. Then when we say that losing this fear might help in embracing the reality itself and being “happy”, we might not be completely wrong. But is the fear something to be conquered? Probably not; the fear from abandoning the ideology is at the core, the fear of abandoning your existence as discussed earlier; but let’s say we completely demolish this fear, then what is left? Certainly not you or even the idea of you. This is because having an idea of yourself is a very primary trait of being alive and has a streak of arrogance in it. Is the self so petty as to need an idea of self while not even realising what self might be. Perhaps having even an inkling of what the self might be would prevent this idea of self from existing. Acceptance is the natural step in conquering fear. However, this acceptance would eventually collapse the entire ego and the self. Is this the same as death, is it even achievable? I do not know, but probably not. Then is the best we can do is simplify the complexities involved and figure out what might be causing this fear at the high level to begin going into the process of even understading it? No, but it is certainly a good point to start.

* Desires
Let’s explore this fear at a high level now since delving deep into the abyss has only raised more questions. As we discussed earlier, one “desires” a better or sustainable tomorrow, but what entails this betterment might be very different for each individual. Whatever these desires may be, these may be the easiest things to control so far, and doing this may also lead to being free of the desire of the better tomorrow and subsequently, the fear itself. This is what one would think, but isn’t being free of desires also a desire itself? As long as one continues to think of getting rid of these desires, he is only substituting one desire with another. To continue living is to indulge in desires - the desire to live, the desire to breathe, the desire to exist, we cannot deny that. So is the only solution of being free of fear dying? That is a reasonable solution and it probably works as well but do we really need to eliminate this fear? Well, objectively speaking, we do not “need” to do anything, “need” is nothing but an unavoidable desire; but addressing the question with another question - would eliminating fear, eliminate the desires and the self containing them, and subsequently simulate a state similar to that of death? Let me correct my earlier sentence, living is to indulge in fear and grief, for the lack of grief is very attractive. If there was no grief, there would not be any lack of it either; happiness is only a state achievable with the presence of grief. This dichotomy is what drives fear and it is not possible to live outside this very basic dichotomy.

* Fear
Fear is something that cannot be eliminated without eliminating oneself. As stated earlier, thinking about eliminating fear is nothing but fearing having fear itself. It is not enough to accept and identify this fear to do something about it; as this will only lead to more fears and thus creating an illusion of seeing fear as a separate entity. One must understand that one is one’s fear itself. Trying to change this fear or trying to change oneself will only deepen the illusion; but when one realises the fear itself, the entire perspective is changed. Now one is the fear, and inevitably one is bound to undergo changes and when I say changes, I do not mean voluntary or changes by desires; since those are nothing but illusion of changes and the idea of the self. If you read this entire piece so far, and can only take away one thing from it, please realise that thinking of yourself or anything as a separate entity gives rise to this another so called entity called “fear” and you cannot just try to be one with it by wanting and trying to be one with it, for there is no “you” but an already inseparable entity.
