---
title: Filthy - 1
author: AlpaViraam
published: November 1, 2022
tags: poetry, filthy
---

* 1
#+begin_verse
Trying to be calm
Trying to be stealthy
Rodents of the war
Sneaking by the wealthy
What is up with this vanity
Why is this all so filthy?

Kindness was fraught
Or so were we taught
Mother was frail
Father no worth more than nought
We raise our heads to our golden God
And pretend to feel his affirming nod.
#+end_verse

#+begin_export html
<!--more-->
#+end_export

#+begin_verse

The kind nod was interrupted
All prayers utterly disrupted
Stood there quietly the dandy man
His dead man's ledger in his hand
The royal gylph of inclination
Told the rabid dog's next decision.

The jaded old man killd abruptly
The dog, no the fox moved oh so subtly
At least the poor man went away smiling
Quiet were the tides of the misery riling
Ma was horrified, desiring all but death
Oh but she was spared.
She would have liked the former nonetheless.

The dog had pups and the pups were fierce
The harlot was taken surrounded by the spears
Left was an animal, so very strange
Might he be worth some silver change
Look at him cry, look at him quiver
Collar, but no clothes, look at him shiver.
#+end_verse
